name: Run Flow Scanner
description: Scan Salesforce Flows for best practices, security, and performance issues.
branding:
  icon: zap
  color: purple
inputs:
  GITHUB_TOKEN:
    description: GitHub token with `contents:read` and `security-events:write` permissions
    required: true
    default: ${{ github.token }}

  threshold:
    description: |
      Minimum severity to fail the action in **table** mode (note, warning, error).
      **Ignored in `sarif` mode** — any result fails the action.
      Optional — no default.
    required: false

  outputMode:
    description: |
      Output format:
      - `sarif` (default): Uploads to GitHub Code Scanning. **Fails on any result**.
      - `table`: Logs results in console. Fails only if severity >= `threshold`.
    required: false
    default: sarif

outputs:
  sarifPath:
    description: Path to the generated SARIF file (only in `sarif` mode)
  scanResults:
    description: Array of scan results in table format (only in `table` mode)

runs:
  using: node20
  main: dist/index.js

author: Ruben Halman